name: MovecraftMultiworldExtensions
version: ${project.version}
description: Extensions for Movecraft multiworld including circumnavigation and automatic world switching
authors: [TrollyLoki]
main: net.trollyloki.movecraftmultiworldextensions.MovecraftMultiworldExtensions

depend: [Movecraft]
softdepend: [WorldGuard]